stages:
  - build
  - test
  - build_production
  - build_docker
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - vendor/
  - node_modules/
  - resources/assets/vendor

.standard_build_and_execution: &standard_build_and_execution
# build and execute a docker image, use variables 
# INSTANCE_PREFIX => the prefix of the docker container/image to be used
# BUILD_LOCATION => the folder where the base tar.gz file is located
# DOCKER_LOCATION => the folder where to run the docker-compose commands
  when: manual
  stage: deploy
  tags:
    - shell
  script: 
    - cp ${BUILD_LOCATION}/klink-dms-$CI_BUILD_REF_NAME.tar.gz ${DOCKER_LOCATION}/dms/downloads/dms.tar.gz
    - cd ${DOCKER_LOCATION}
    - docker-compose -f klink-services.yml -p ${INSTANCE_PREFIX} build dmsproject
    - docker-compose -f docker-compose-kbox.yml -p ${INSTANCE_PREFIX} stop && docker-compose -f docker-compose-kbox.yml -p ${INSTANCE_PREFIX} rm -v -f && docker-compose -f docker-compose-kbox.yml -p ${INSTANCE_PREFIX} up -d frontend


build_dev:
# performs only composer install with dev dependencies
  stage: build
  script:
    - mv env.ci .env
    - composer install --prefer-dist
    - mv .env env.ci
  tags:
    - php
    - nodejs
    - shell
    
linting:
# check if the php files contains syntax error and mess-detector
  stage: test
  script:
    - mv env.ci .env
    - ./vendor/bin/parallel-lint --exclude vendor .
    - mv .env env.ci
  tags:
    - php
    - nodejs
    - shell

build_prod:
# perform the build to be used in production
  stage: build_production
  script:
    - mv env.ci .env
    - composer install --no-dev --prefer-dist
    - npm install
    - node_modules/.bin/bower install
    - node_modules/.bin/gulp --production
    - php artisan dms:lang-publish
    - mv .env env.ci
    - sed -i "s/BUILDCODE/${CI_BUILD_REF}/g" ./config/dms.php
    - tar --transform 's,^.,dms,' -cz . $TAR_PARAMETERS > ${BUILD_FOLDER}/klink-dms-$CI_BUILD_REF_NAME.tar.gz
  tags:
    - php
    - nodejs
    - shell

    
test_klink_asia_deploy:
# creates the DMS docker image and restart the test instance with the new image
  environment: Review
  <<: *standard_build_and_execution
  except:
    - master
    - release
  variables:
    INSTANCE_PREFIX: $TEST_INSTANCE_PREFIX
    BUILD_LOCATION: $BUILD_FOLDER 
    DOCKER_LOCATION: $TEST_DOCKER_FOLDER 


dms_klink_asia_deploy:
# creates the DMS docker image and restart the DMS.klink.asia instance with the new image
  stage: deploy
  environment: Staging
  script:
    - cp ${BUILD_FOLDER}/klink-dms-$CI_BUILD_REF_NAME.tar.gz ${PROD_DOCKER_FOLDER}/dms/downloads/dms.tar.gz
    - cd ${PROD_DOCKER_FOLDER}
    - docker-compose -f klink-services.yml build dmsproject 
    - docker-compose -f ${PROD_DOCKER_FOLDER}/docker-compose-kbox.yml stop && docker-compose -f ${PROD_DOCKER_FOLDER}/docker-compose-kbox.yml rm -v -f && docker-compose -f ${PROD_DOCKER_FOLDER}/docker-compose-kbox.yml up -d frontend
  when: manual
  only:
    - master
    - release
  tags:
    - shell